### ISSUE TITLE
Fix flaky WellKnownTypesTest junit tests

### ISSUE THREAD

**Issue by mscheong01** [mscheong01/krotoDC#13]
WellKnownTypesTest pass in local development environment, but fails in CI
<img width="511" alt="image" src="https://github.com/mscheong01/krotoDC/assets/54794500/55392d44-ba62-4f7b-b5b5-0e77ce9b1914">
<img width="778" alt="image" src="https://github.com/mscheong01/krotoDC/assets/54794500/a079a13e-02ac-4c72-9626-0530d236faa4">

**Comment by Dogacel** [comment]
This is actually not a flaky test, you wrote the tests regarding to your timezone. Those tests did not work in my local because I live in GMT+3.

The `LocalDateTime` is actually independent of timezone. Thus it should be converted using UTC time.
- #20

**Comment by mscheong01** [comment]
@Dogacel You're right 😓 These tests would only succeed in UTC+9:00 which is my local timezone. Thanks for pointing it out 🙇‍♂️
