### ISSUE TITLE
Using with `protoc` cli

### ISSUE THREAD

**Issue by inkeliz** [mscheong01/krotoDC#31]
I'm not used to Gradle (actually, I hate the Android/Java/Kotlin ecosystem), and I would like to stick with `protoc`, since I'm using multiple languages, so it shares the same `.proto` and a single `Makefile`.

I'm interested to try `KrotoDC`, since the default code generation is very annoying to use. The `README` only describes how to use it as a plugin. How can I use it directly with `protoc`, so I can use `protoc -I="." --java_out="kotlin" --kotlin_out="kotlin" --proto_path="." "envelope.proto"` and use KrotoDC instead of the the default one?!

**Comment by mscheong01** [comment]
Hi @inkeliz 👋 
You can use the plugin by adding a script file and specifying it as a protoc plugin
ex)
```cmd
:: run-krotoDC.cmd
@ECHO OFF
java -jar protoc-gen-krotodc-1.0.1-jdk8.jar %*
```
usage:
```bash
 protoc --plugin=protoc-gen-krotoDC=run-krotoDC.cmd --krotoDC_out=. test.proto
```
writing a script file may seem a bit hacky, but it's actually how the official gradle plugin works internally 
(reference: https://github.com/google/protobuf-gradle-plugin/blob/12ad3185175fbe49a7d65dbb503a5598e214989b/src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy#L734)

Please let me know if you have any problems with this approach 🙂

**Comment by inkeliz** [comment]
Thanks. It solves the issue, I got the generated files. But, seems to be broken. :(

````
package com.example.myapplication2.`data`.krotodc

import com.google.protobuf.ByteString
import io.github.mscheong01.krotodc.KrotoDC

@KrotoDC(forProto = com.example.myapplication2.`data`.Envelope.Envelope::class)
public data class Envelope(
  public val publicKey: ByteString = com.google.protobuf.ByteString.EMPTY,
  public val signature: ByteString = com.google.protobuf.ByteString.EMPTY,
  public val content: ByteString = com.google.protobuf.ByteString.EMPTY,
) {
  public companion object
}
````

The line (``@KrotoDC(forProto = com.example.myapplication2.`data`.Envelope.Envelope::class)``) reports `An annotation argument must be a compile-time constant`. 

Assuming that the path is: `com.example.myapplication2.data`, it's suppose to have files in there, or just a folder of `krotodc`?

**Comment by mscheong01** [comment]
@inkeliz Since krotoDC generated classes work as a wrapper around Java protobufs, they have to be generated along with each other. Specifying --java_out option to the same directory will probably fix the issue 🤔

**Comment by inkeliz** [comment]
Thanks. That solves the issue. I had one issue due to the name of one `proto`, the name was `envelope.proto` and it has one `message Envelope`, which causes the generator to name it as `EnvelopeOuterClass`. I don't know why, maybe a Java/Kotlin stuff. Naming it to `Enveloping.proto` works. :D
