### ISSUE TITLE
Update jar versions

### ISSUE THREAD

**Issue by pambrose** [mscheong01/krotoDC#33]
Hi,

Do you anticipate updating the versions of kotlin and grpc in this library anytime soon?

Thanks,
Paul

**Comment by mscheong01** [comment]
Hello 👋 
There has been a setback regarding the version update of protocol buffers (#32) But I think we can upgrade the rest of the project including kotlin 2.

**Comment by pambrose** [comment]
Thanks a lot!!

**Comment by mscheong01** [comment]
I'm having trouble publishing the new version (some bug related to the checkout workflow https://github.com/actions/checkout/issues/664) 😭 
I'll let you know here when the release is out for good.

**Comment by pambrose** [comment]
Was this resolved?
